# Generated by Django 4.2.26 on 2026-01-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0012_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus'), ('CHARACTER_IDENTIFIER', 'Character Identifier'), ('GENERATE_NARRATION', 'Generate Narration'), ('GENERATE_DUBBING', 'Generate Dubbing'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script'), ('LOCALIZE_NARRATION', 'Localize Narration'), ('SUBTITLE_CONTEXT', 'Subtitle Context Analysis'), ('CHARACTER_PRE_ANNOTATOR', 'Character Pre-Annotator'), ('SCENE_PRE_ANNOTATOR', 'Scene Pre-Annotator'), ('VISUAL_ANALYZER', 'Visual Analyzer'), ('SLICE_GROUPER', 'Slice Grouper'), ('SUBTITLE_MERGER', 'Subtitle Merger'), ('SLICE_REGROUPER', 'Slice Regrouper')], max_length=30, verbose_name='Task Type'),
        ),
    ]
