# Generated by Django 4.2.26 on 2026-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0018_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus'), ('CHARACTER_IDENTIFIER', 'Character Identifier'), ('GENERATE_NARRATION', 'Generate Narration'), ('GENERATE_DUBBING', 'Generate Dubbing'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script'), ('LOCALIZE_NARRATION', 'Localize Narration'), ('SUBTITLE_CONTEXT', 'Subtitle Context Analysis'), ('CHARACTER_PRE_ANNOTATOR', 'Character Pre-Annotator'), ('SCENE_PRE_ANNOTATOR', 'Scene Pre-Annotator'), ('VISUAL_ANALYZER', 'Visual Analyzer'), ('SUBTITLE_MERGER', 'Subtitle Merger'), ('SLICE_REGROUPER', 'Slice Regrouper'), ('REFINERY_SUBTITLE_MERGER', '[Refinery] Subtitle Merger'), ('REFINERY_CHARACTER_IDENTIFIER', '[Refinery] Character Identifier'), ('REFINERY_VISUAL_ANALYZER', '[Refinery] Visual Analyzer'), ('REFINERY_SLICE_REGROUPER', '[Refinery] Slice Regrouper')], db_index=True, max_length=64, verbose_name='Task Type'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['organization', '-created'], name='task_manage_organiz_8169e2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='task_manage_status_88681e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created'], name='task_manage_created_c050bc_idx'),
        ),
    ]
