# Generated by Django 4.2.26 on 2026-01-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0021_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('DEPLOY_RAG_CORPUS', 'Deploy RAG Corpus'), ('CHARACTER_IDENTIFIER', 'Character Identifier'), ('GENERATE_NARRATION', 'Generate Narration'), ('GENERATE_DUBBING', 'Generate Dubbing'), ('GENERATE_EDITING_SCRIPT', 'Generate Editing Script'), ('LOCALIZE_NARRATION', 'Localize Narration'), ('SUBTITLE_CONTEXT', 'Subtitle Context Analysis'), ('REFINERY_SUBTITLE_MERGER', '[Refinery] Subtitle Merger'), ('REFINERY_CHARACTER_IDENTIFIER', '[Refinery] Character Identifier'), ('REFINERY_VISUAL_ANALYZER', '[Refinery] Visual Analyzer'), ('REFINERY_SLICE_REGROUPER', '[Refinery] Slice Regrouper'), ('REFINERY_SLICE_ANALYZER', '[Refinery] Slice Analyzer'), ('REFINERY_DUBBING_SCRIPT_REFINER', '[Refinery] Dubbing Script Refiner'), ('CREATIVE_ASSET_SELECTOR', '[Creative] Asset Selector'), ('CREATIVE_EDITING_DIRECTOR', '[Creative] Editing Director')], db_index=True, max_length=64, verbose_name='Task Type'),
        ),
    ]