# Generated by Django 4.2.26 on 2026-02-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0023_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='error',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Error'),
        ),
    ]
